import 'dart:ui';
import 'package:flutter_hms_dashboard_ui/core/styles/app_colors.dart';
import 'package:flutter_hms_dashboard_ui/features/departments/models/departments.dart';

class DepartmentsData {
  // ignore: constant_identifier_names
  static const List<Department> Menu = [
    Department(
      id: 1,
      title: 'General',
      image: 'assets/images/departments_icons/16-General.png',
      bgImageName: '',
      bgColor: Color.fromARGB(255, 238, 152, 94),
    ),
    Department(
      id: 2,
      title: 'OPD',
      image: 'assets/images/departments_icons/17-OPD.png',
      bgImageName: '',
      bgColor: AppColors.yellow,
    ),
    Department(
      id: 3,
      title: 'ER',
      image: 'assets/images/departments_icons/18-ER.png',
      bgImageName: '',
      bgColor: Color.fromARGB(255, 209, 75, 72),
    ),
    Department(
      id: 4,
      title: 'Radiology',
      image: 'assets/images/departments_icons/05-radiology.png',
      bgImageName: '',
      bgColor: AppColors.orangeDark,
    ),
    Department(
      id: 5,
      title: 'IPD',
      image: 'assets/images/departments_icons/20-IPD.png',
      bgImageName: '',
      bgColor: AppColors.green,
    ),
    Department(
      id: 6,
      title: 'Lab',
      image: 'assets/images/departments_icons/21-Lab.png',
      bgImageName: '',
      bgColor: AppColors.sugar,
    ),
    Department(
      id: 7,
      title: 'Patients Diet',
      image: 'assets/images/departments_icons/04-food-&-nutrition-system.png',
      bgImageName: '',
      bgColor: AppColors.orangeDark,
    ),
    Department(
      id: 8,
      title: 'Inventory',
      image: 'assets/images/departments_icons/23-Inventory.png',
      bgImageName: '',
      bgColor: Color.fromARGB(255, 116, 138, 233),
    ),
    Department(
      id: 9,
      title: 'Purchase & payables',
      image: 'assets/images/departments_icons/24-Purchase&payables.png',
      bgImageName: '',
      bgColor: Color.fromARGB(255, 212, 154, 37),
    ),
    Department(
      id: 10,
      title: 'Financial Accounts',
      image: 'assets/images/departments_icons/03-finance.png',
      bgImageName: '',
      bgColor: AppColors.yellow,
    ),
    Department(
      id: 11,
      title: 'CWS',
      image: 'assets/images/departments_icons/26-CWS.png',
      bgImageName: '',
      bgColor: AppColors.honey,
    ),
    Department(
      id: 12,
      title: 'Pharmacy',
      image: 'assets/images/departments_icons/27-Pharmacy.png',
      bgImageName: '',
      bgColor: AppColors.sugar,
    ),
    Department(
      id: 13,
      title: 'Equipment Maintenance',
      image: 'assets/images/departments_icons/28-Equipment Maintenance.png',
      bgImageName: '',
      bgColor: AppColors.red,
    ),
    Department(
      id: 14,
      title: 'Patient History',
      image: 'assets/images/departments_icons/29-Patient History.png',
      bgImageName: '',
      bgColor: AppColors.sugar,
    ),
    Department(
      id: 15,
      title: 'Administration',
      image: 'assets/images/departments_icons/30-Administration.png',
      bgImageName: '',
      bgColor: AppColors.sugar,
    ),
    ////////////////////////////////////////////////////////////////////////////
    ///////////////////^^DEPARTMENTS ACCORDING TO WEBSITE^^/////////////////////
    ////////////////////////////////////////////////////////////////////////////
    Department(
      id: 16,
      title: 'Billing',
      image: 'assets/images/departments_icons/01-billing.png',
      bgImageName: '',
      bgColor: AppColors.yellow,
    ),
    // Department(
    //   id: 17,
    //   title: 'Radiology',
    //   image: 'assets/images/departments_icons/05-radiology.png',
    //   bgImageName: '',
    //   bgColor: AppColors.primary,
    // ),
    Department(
      id: 18,
      title: 'Medical Records',
      image: 'assets/images/departments_icons/08-medical-records.png',
      bgImageName: '',
      bgColor: AppColors.pinkLight,
    ),
    Department(
      id: 19,
      title: 'Security Systems',
      image: 'assets/images/departments_icons/02-security-systems.png',
      bgImageName: '',
      bgColor: AppColors.orangeDark,
    ),
    Department(
      id: 20,
      title: 'Personal Information System',
      image: 'assets/images/departments_icons/09-personal-information-system.png',
      bgImageName: '',
      bgColor: AppColors.green,
    ),
    // Department(
    //   id: 21,
    //   title: 'Finance',
    //   image: 'assets/images/departments_icons/03-finance.png',
    //   bgImageName: '',
    //   bgColor: AppColors.sugar,
    // ),
    Department(
      id: 22,
      title: 'Dialysis system',
      image: 'assets/images/departments_icons/13-dialysis-system.png',
      bgImageName: '',
      bgColor: AppColors.red,
    ),
    // Department(
    //   id: 23,
    //   title: 'Food & nutrition system',
    //   image: 'assets/images/departments_icons/04-food-&-nutrition-system.png',
    //   bgImageName: '',
    //   bgColor: AppColors.orangeDark,
    // ),
    Department(
      id: 24,
      title: 'Budget Variance',
      image: 'assets/images/departments_icons/06-budget-variance.png',
      bgImageName: '',
      bgColor: AppColors.sugar,
    ),
    Department(
      id: 25,
      title: 'Cash Counter',
      image: 'assets/images/departments_icons/14-cash-counter.png',
      bgImageName: '',
      bgColor: AppColors.yellow,
    ),
    Department(
      id: 26,
      title: 'Consultation clinic system',
      image: 'assets/images/departments_icons/07-consultation-clinic-system.png',
      bgImageName: '',
      bgColor: AppColors.honey,
    ),
    Department(
      id: 27,
      title: 'Patient Administration System',
      image: 'assets/images/departments_icons/11-patient-administration-system.png',
      bgImageName: '',
      bgColor: AppColors.sugar,
    ),
    Department(
      id: 28,
      title: 'Patient Registration System',
      image: 'assets/images/departments_icons/10-patient-registration-system.png',
      bgImageName: '',
      bgColor: AppColors.red,
    ),
    Department(
      id: 29,
      title: 'Library Management System',
      image: 'assets/images/departments_icons/12-library-management-system.png',
      bgImageName: '',
      bgColor: AppColors.orangeDark,
    ),
    Department(
      id: 30,
      title: 'Donation System',
      image: 'assets/images/departments_icons/15-donation-system.png',
      bgImageName: '',
      bgColor: AppColors.sugar,
    ),
    Department(
      id: 31,
      title: 'Marketing',
      image: 'assets/images/departments_icons/31-Marketing.png',
      bgImageName: '',
      bgColor: Color.fromARGB(255, 105, 89, 243),
    ),
  ];
}
